In [1]:
items =['pen','paper','stop','book','eraser']
for ele in items:
    if ele == 'stop':
        break
    print(ele)
print('loop ended')

pen
paper
loop ended


In [2]:
secret_password = 'python'
password =input("enter your password")
while password != secret_password:
    print("incorrect password")
    password = input("enter your password again")
print("access granted")

incorrect password
access granted


In [13]:
import numpy as np
numbers = np.random.randint(45,105,size=(5,4))
print(numbers)

[[103  84  99  91]
 [104 101 104  54]
 [103  76  61  88]
 [ 55  75  49  52]
 [ 97  99  53  76]]


In [12]:
import numpy as np
my_list = np.random.rand(45,105,size=(5,4))
for i in range(len(my_list)):
        my_list[i] += 5
print(my_list)

TypeError: rand() got an unexpected keyword argument 'size'

In [16]:
import numpy as np
numbers = np.random.randint(45,105,size=(5,4))
print(numbers)

[[ 45  58  81  49]
 [ 57  45  52  94]
 [ 85 103  97 101]
 [ 75  58  57  50]
 [ 95  70  57  75]]


In [17]:
for i in range(0,len(numbers)):
    print(f'\n Row number:{i}')
    for j in range(0,len(numbers[i])):
        print(f'ele index -> {i},{j} and ele value -> {numbers[i][j]}')
        numbers[i][j] = numbers[i][j]+5


 Row number:0
ele index -> 0,0 and ele value -> 45
ele index -> 0,1 and ele value -> 58
ele index -> 0,2 and ele value -> 81
ele index -> 0,3 and ele value -> 49

 Row number:1
ele index -> 1,0 and ele value -> 57
ele index -> 1,1 and ele value -> 45
ele index -> 1,2 and ele value -> 52
ele index -> 1,3 and ele value -> 94

 Row number:2
ele index -> 2,0 and ele value -> 85
ele index -> 2,1 and ele value -> 103
ele index -> 2,2 and ele value -> 97
ele index -> 2,3 and ele value -> 101

 Row number:3
ele index -> 3,0 and ele value -> 75
ele index -> 3,1 and ele value -> 58
ele index -> 3,2 and ele value -> 57
ele index -> 3,3 and ele value -> 50

 Row number:4
ele index -> 4,0 and ele value -> 95
ele index -> 4,1 and ele value -> 70
ele index -> 4,2 and ele value -> 57
ele index -> 4,3 and ele value -> 75


In [18]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from scipy import stats
sample_data = [495,485,501]

In [19]:
pip install statsmodels


     ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
     ---------------------------------------- 0.0/9.6 MB 660.6 kB/s eta 0:00:15
     ---------------------------------------- 0.1/9.6 MB 975.2 kB/s eta 0:00:10
      --------------------------------------- 0.1/9.6 MB 1.2 MB/s eta 0:00:08
      --------------------------------------- 0.2/9.6 MB 1.3 MB/s eta 0:00:08
      --------------------------------------- 0.2/9.6 MB 1.2 MB/s eta 0:00:08
     - -------------------------------------- 0.3/9.6 MB 1.0 MB/s eta 0:00:09
     - -------------------------------------- 0.3/9.6 MB 1.0 MB/s eta 0:00:10
     - -------------------------------------- 0.3/9.6 MB 1.0 MB/s eta 0:00:10
     - -------------------------------------- 0.3/9.6 MB 863.3 kB/s eta 0:00:11
     - -------------------------------------- 0.3/9.6 MB 807.1 kB/s eta 0:00:12
     - -------------------------------------- 0.3/9.6 MB 807.1 kB/s eta 0:00:12
     - -------------------------------------- 0.4/9.6 MB 768.


[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
